const contactData = [
  {
    id: '1',
    avatar: '/images/profiles/player1.jpg',
    avatar2: '/images/profiles/player2.jpg',
    name: 'Fernando Gonzalez',
    name2: 'Ricardo Salas',
    MarcadorJugador1: '5',
    MarcadorJugador2: '8',
    Ganador: 'Ricardo Salas',
    title: 'Administrator',
    phone: '+6281234567890',
    secondaryPhone: '+6280987654321',
    personalEmail: 'johndoe@mail.com',
    companyEmail: 'johndoe@company.com',
    address: 'Ipsum Street no.77 Block A/5A, New York',
    website: 'http://doeclans.net',
    favorited: false
  },
  {
    id: '2',
    avatar: '/images/profiles/player3.jpg',
    avatar2: '/images/profiles/player4.jpg',
    name: 'Carlos Maya',
    name2: 'Taylor Fritz',
    MarcadorJugador1: '8',
    MarcadorJugador2: '4',
    Ganador: 'Carlos Maya',
    title: 'System Engineer',
    phone: '+657890321145',
    secondaryPhone: '',
    personalEmail: 'jimdoe@mail.com',
    companyEmail: 'jimdoe@company.com',
    address: 'Lorem Street no.76 Block B/8B, Brooklyn',
    website: 'http://doejim.com',
    favorited: true
  },
  {
    id: '3',
    avatar: '/images/profiles/player5.jpg',
    avatar2: '/images/profiles/player6.jpg',
    name: 'Pedro Perez',
    name2: 'Antonio García',
    MarcadorJugador1: '5',
    MarcadorJugador2: '7',
    Ganador: 'Antonio García',
    title: 'Administrator',
    phone: '+6281234567890',
    secondaryPhone: '+6280987654321',
    personalEmail: 'johndoe@mail.com',
    companyEmail: 'johndoe@company.com',
    address: 'Ipsum Street no.77 Block A/5A, New York',
    website: 'http://doeclans.net',
    favorited: false
  },
  {
    id: '4',
    avatar: '/images/profiles/player7.jpg',
    avatar2: '/images/profiles/player9.jpg',
    name: 'Cesar Torres',
    name2: 'Raúl Parra',
    MarcadorJugador1: '8',
    MarcadorJugador2: '1',
    Ganador: 'Cesar Torres',
    title: 'System Engineer',
    phone: '+657890321145',
    secondaryPhone: '',
    personalEmail: 'jimdoe@mail.com',
    companyEmail: 'jimdoe@company.com',
    address: 'Lorem Street no.76 Block B/8B, Brooklyn',
    website: 'http://doejim.com',
    favorited: true
  },
  {
    id: '5',
    avatar: '/images/profiles/player8.jpg',
    avatar2: '/images/profiles/player10.jpg',
    name: 'Fernando Gonzalez',
    name2: 'Ricardo Salas',
    MarcadorJugador1: '5',
    MarcadorJugador2: '8',
    Ganador: 'Ricardo Salas',
    title: 'Administrator',
    phone: '+6281234567890',
    secondaryPhone: '+6280987654321',
    personalEmail: 'johndoe@mail.com',
    companyEmail: 'johndoe@company.com',
    address: 'Ipsum Street no.77 Block A/5A, New York',
    website: 'http://doeclans.net',
    favorited: false
  },
];

export default contactData;
